#!/usr/bin/env python3
"""Generate the Ocean color LUT used by the map's "Ocean" theme.

Mapbox Standard has no built-in ocean theme, so the Ocean look is a custom
color LUT: a 32x32x32 RGB cube flattened to a 1024x32 PNG and base64-encoded,
applied via setConfigProperty('basemap', 'theme-data', ...). The warp below
pushes every map color toward deep ocean blue-teal, strongest in the shadows
and midtones and fading out in highlights so labels stay legible.

Usage (needs Pillow):
    python tools/make_ocean_lut.py

It rewrites js/ocean-lut.js in place. Tune the warp() constants to adjust the
tint, then re-run. theme-data (a custom LUT) requires Mapbox GL JS v3.9+.
"""
import base64
import io
import os

from PIL import Image

N = 32  # cube size per channel; image is (N*N) wide x N tall


def warp(r, g, b):
    """Map an identity RGB triple (0..1) toward the ocean palette."""
    lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
    tint = (1.0 - lum) ** 1.2  # strong in shadows/mids, ~0 in highlights
    tr = r * (1 - 0.55 * tint)              # cut red
    tg = g * (1 - 0.15 * tint) + 0.10 * tint  # keep some green -> teal
    tb = b + 0.28 * tint                     # lift blue
    clamp = lambda v: max(0.0, min(1.0, v))
    return clamp(tr), clamp(tg), clamp(tb)


def build_png_bytes():
    img = Image.new("RGB", (N * N, N))
    px = img.load()
    for bi in range(N):
        for gi in range(N):
            for ri in range(N):
                r, g, b = ri / (N - 1), gi / (N - 1), bi / (N - 1)
                wr, wg, wb = warp(r, g, b)
                px[bi * N + ri, gi] = (round(wr * 255), round(wg * 255), round(wb * 255))
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def main():
    data = base64.b64encode(build_png_bytes()).decode()
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "js", "ocean-lut.js")
    header = (
        "/**\n"
        " * ocean-lut.js - the color lookup table (LUT) that gives the \"Ocean\"\n"
        " * map theme its deep blue-teal tint. GENERATED by tools/make_ocean_lut.py;\n"
        " * edit the warp() there and regenerate rather than editing this file.\n"
        " *\n"
        " * It is the Mapbox Standard \"custom\" theme's data: a 32x32x32 color cube\n"
        " * flattened to a 1024x32 PNG, base64-encoded. map.js applies it with\n"
        " * setConfigProperty('basemap','theme-data', KPR.OCEAN_LUT). Requires GL JS v3.9+.\n"
        " */\n"
        "window.KPR = window.KPR || {};\n"
    )
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write('KPR.OCEAN_LUT = "data:image/png;base64,' + data + '";\n')
    print("wrote", os.path.normpath(out), "(", len(data), "base64 chars )")


if __name__ == "__main__":
    main()
